//! @generated by `frood gen` from `/Users/amal/dev/.scratch/2026/06/14/vesting-position/babelfish-tests/idls/vesting_positions.codama.json`. Regenerate; do not edit.
//!
//! Typed mirrors over the dynamic core: every builder lowers to the same
//! account entries and `Value` the stringly form uses, at the border.
#![allow(clippy::all)]

use frood::{BuiltIx, IntoBundle, Story};
use frood_idl::types::{IntoAccountKey, TypedIx, Value};
use solana_pubkey::Pubkey;

/// Field paths of the `campaign` account, for `Story::track_at`.
pub mod campaign {
    #[allow(unused_imports)] pub(crate) use frood_idl::types::{FieldPath, Value};
    #[allow(unused_imports)] pub(crate) use solana_pubkey::Pubkey;
    /// `campaign.creator` (projects as `Pubkey`), for `Story::track_at`.
    pub const CREATOR: FieldPath<Pubkey> = FieldPath::new("campaign", "creator");
    /// `campaign.merkleRoot` (projects as `Vec<u8>`), for `Story::track_at`.
    pub const MERKLE_ROOT: FieldPath<Vec<u8>> = FieldPath::new("campaign", "merkleRoot");
    /// `campaign.start` (projects as `i64`), for `Story::track_at`.
    pub const START: FieldPath<i64> = FieldPath::new("campaign", "start");
    /// `campaign.end` (projects as `i64`), for `Story::track_at`.
    pub const END: FieldPath<i64> = FieldPath::new("campaign", "end");
    /// `campaign.cliffDuration` (projects as `u64`), for `Story::track_at`.
    pub const CLIFF_DURATION: FieldPath<u64> = FieldPath::new("campaign", "cliffDuration");
    /// `campaign.cliffReleaseBps` (projects as `u16`), for `Story::track_at`.
    pub const CLIFF_RELEASE_BPS: FieldPath<u16> = FieldPath::new("campaign", "cliffReleaseBps");
    /// `campaign.mintToDistribute` (projects as `Pubkey`), for `Story::track_at`.
    pub const MINT_TO_DISTRIBUTE: FieldPath<Pubkey> = FieldPath::new("campaign", "mintToDistribute");
    /// `campaign.isTransferable` (projects as `bool`), for `Story::track_at`.
    pub const IS_TRANSFERABLE: FieldPath<bool> = FieldPath::new("campaign", "isTransferable");
    /// `campaign.gracePeriod` (projects as `u64`), for `Story::track_at`.
    pub const GRACE_PERIOD: FieldPath<u64> = FieldPath::new("campaign", "gracePeriod");
    /// `campaign.totalDeposit` (projects as `u64`), for `Story::track_at`.
    pub const TOTAL_DEPOSIT: FieldPath<u64> = FieldPath::new("campaign", "totalDeposit");
    /// `campaign.collection` (projects as `Pubkey`), for `Story::track_at`.
    pub const COLLECTION: FieldPath<Pubkey> = FieldPath::new("campaign", "collection");
    /// `campaign.campaignBump` (projects as `u8`), for `Story::track_at`.
    pub const CAMPAIGN_BUMP: FieldPath<u8> = FieldPath::new("campaign", "campaignBump");
    /// `campaign.collectionBump` (projects as `u8`), for `Story::track_at`.
    pub const COLLECTION_BUMP: FieldPath<u8> = FieldPath::new("campaign", "collectionBump");
    /// `campaign.authBump` (projects as `u8`), for `Story::track_at`.
    pub const AUTH_BUMP: FieldPath<u8> = FieldPath::new("campaign", "authBump");
}

/// Field paths of the `claimReceipt` account, for `Story::track_at`.
pub mod claim_receipt {
    #[allow(unused_imports)] pub(crate) use frood_idl::types::{FieldPath, Value};
    #[allow(unused_imports)] pub(crate) use solana_pubkey::Pubkey;
    /// `claimReceipt.claimer` (projects as `Pubkey`), for `Story::track_at`.
    pub const CLAIMER: FieldPath<Pubkey> = FieldPath::new("claimReceipt", "claimer");
}

/// Typed builder for the `cancelCampaign` instruction of `vestingPositions`,
/// generated by `frood gen` from the program's Codama IDL. Each account
/// method is a compile-checked schema name; hand the builder to `Story::when`,
/// which lowers it to the same dynamic call the stringly form makes.
#[derive(Default)]
pub struct CancelCampaign {
    accounts: Vec<(&'static str, Pubkey)>,
    args: Vec<(String, Value)>,
}

/// Start a typed `cancelCampaign` instruction (see [`CancelCampaign`]).
///
/// Generated from `vestingPositions`'s Codama IDL; run it with `Story::when`.
pub fn cancel_campaign() -> CancelCampaign {
    CancelCampaign::default()
}

impl CancelCampaign {
    /// The `creator` account of `cancelCampaign` (signer, writable).
    ///
    /// Typed helper on [`CancelCampaign`], from the IDL's instructionAccountNode;
    /// takes a `Pubkey`, `&Pubkey`, or a cast member (`&Actor`).
    pub fn creator(mut self, key: impl IntoAccountKey) -> Self {
        self.accounts.push(("creator", key.into_account_key()));
        self
    }
    /// The `campaign` account of `cancelCampaign` (writable; optional: omit it and the resolver fills the schema's default).
    ///
    /// Typed helper on [`CancelCampaign`], from the IDL's instructionAccountNode;
    /// takes a `Pubkey`, `&Pubkey`, or a cast member (`&Actor`).
    pub fn campaign(mut self, key: impl IntoAccountKey) -> Self {
        self.accounts.push(("campaign", key.into_account_key()));
        self
    }
    /// The `collection` account of `cancelCampaign` (writable).
    ///
    /// Typed helper on [`CancelCampaign`], from the IDL's instructionAccountNode;
    /// takes a `Pubkey`, `&Pubkey`, or a cast member (`&Actor`).
    pub fn collection(mut self, key: impl IntoAccountKey) -> Self {
        self.accounts.push(("collection", key.into_account_key()));
        self
    }
    /// The `updateAuthority` account of `cancelCampaign` (writable; optional: omit it and the resolver fills the schema's default).
    ///
    /// Typed helper on [`CancelCampaign`], from the IDL's instructionAccountNode;
    /// takes a `Pubkey`, `&Pubkey`, or a cast member (`&Actor`).
    pub fn update_authority(mut self, key: impl IntoAccountKey) -> Self {
        self.accounts.push(("updateAuthority", key.into_account_key()));
        self
    }
    /// The `mint` account of `cancelCampaign` (readonly).
    ///
    /// Typed helper on [`CancelCampaign`], from the IDL's instructionAccountNode;
    /// takes a `Pubkey`, `&Pubkey`, or a cast member (`&Actor`).
    pub fn mint(mut self, key: impl IntoAccountKey) -> Self {
        self.accounts.push(("mint", key.into_account_key()));
        self
    }
    /// The `campaignAta` account of `cancelCampaign` (writable; optional: omit it and the resolver fills the schema's default).
    ///
    /// Typed helper on [`CancelCampaign`], from the IDL's instructionAccountNode;
    /// takes a `Pubkey`, `&Pubkey`, or a cast member (`&Actor`).
    pub fn campaign_ata(mut self, key: impl IntoAccountKey) -> Self {
        self.accounts.push(("campaignAta", key.into_account_key()));
        self
    }
    /// The `creatorAta` account of `cancelCampaign` (writable; optional: omit it and the resolver fills the schema's default).
    ///
    /// Typed helper on [`CancelCampaign`], from the IDL's instructionAccountNode;
    /// takes a `Pubkey`, `&Pubkey`, or a cast member (`&Actor`).
    pub fn creator_ata(mut self, key: impl IntoAccountKey) -> Self {
        self.accounts.push(("creatorAta", key.into_account_key()));
        self
    }
    /// The `systemProgram` account of `cancelCampaign` (readonly; optional: omit it and the resolver fills the schema's default).
    ///
    /// Typed helper on [`CancelCampaign`], from the IDL's instructionAccountNode;
    /// takes a `Pubkey`, `&Pubkey`, or a cast member (`&Actor`).
    pub fn system_program(mut self, key: impl IntoAccountKey) -> Self {
        self.accounts.push(("systemProgram", key.into_account_key()));
        self
    }
    /// The `tokenProgram` account of `cancelCampaign` (readonly; optional: omit it and the resolver fills the schema's default).
    ///
    /// Typed helper on [`CancelCampaign`], from the IDL's instructionAccountNode;
    /// takes a `Pubkey`, `&Pubkey`, or a cast member (`&Actor`).
    pub fn token_program(mut self, key: impl IntoAccountKey) -> Self {
        self.accounts.push(("tokenProgram", key.into_account_key()));
        self
    }
    /// The `associatedTokenProgram` account of `cancelCampaign` (readonly; optional: omit it and the resolver fills the schema's default).
    ///
    /// Typed helper on [`CancelCampaign`], from the IDL's instructionAccountNode;
    /// takes a `Pubkey`, `&Pubkey`, or a cast member (`&Actor`).
    pub fn associated_token_program(mut self, key: impl IntoAccountKey) -> Self {
        self.accounts.push(("associatedTokenProgram", key.into_account_key()));
        self
    }
    /// The `mplCoreProgram` account of `cancelCampaign` (readonly; optional: omit it and the resolver fills the schema's default).
    ///
    /// Typed helper on [`CancelCampaign`], from the IDL's instructionAccountNode;
    /// takes a `Pubkey`, `&Pubkey`, or a cast member (`&Actor`).
    pub fn mpl_core_program(mut self, key: impl IntoAccountKey) -> Self {
        self.accounts.push(("mplCoreProgram", key.into_account_key()));
        self
    }
}

impl TypedIx for CancelCampaign {
    const NAME: &'static str = "cancelCampaign";
    fn lower(self) -> (Vec<(&'static str, Pubkey)>, Value) {
        (self.accounts, Value::Struct(self.args))
    }
}

impl IntoBundle for CancelCampaign {
    fn into_bundle(self, story: &Story) -> Vec<BuiltIx> {
        vec![story.ix_typed(self)]
    }
}

/// Arguments of `claim`: a typed mirror of the instruction's Codama arguments, lowering to the dynamic `Value` at the border.
#[derive(Clone, Debug)]
pub struct ClaimArgs {
    pub proofs: Option<Vec<Vec<u8>>>,
    pub allocation: Option<u64>,
    pub name: String,
    pub uri: String,
}

impl From<ClaimArgs> for Value {
    fn from(v: ClaimArgs) -> Value {
        Value::Struct(vec![
            ("proofs".into(), Value::Option(v.proofs.map(|x| Box::new(Value::Seq(x.into_iter().map(|x| Value::Bytes(x)).collect()))))),
            ("allocation".into(), Value::Option(v.allocation.map(|x| Box::new(Value::U64(x))))),
            ("name".into(), Value::String(v.name)),
            ("uri".into(), Value::String(v.uri)),
        ])
    }
}

/// Typed builder for the `claim` instruction of `vestingPositions`,
/// generated by `frood gen` from the program's Codama IDL. Each account
/// method is a compile-checked schema name; hand the builder to `Story::when`,
/// which lowers it to the same dynamic call the stringly form makes.
#[derive(Default)]
pub struct Claim {
    accounts: Vec<(&'static str, Pubkey)>,
    args: Vec<(String, Value)>,
}

/// Start a typed `claim` instruction (see [`Claim`]).
///
/// Generated from `vestingPositions`'s Codama IDL; run it with `Story::when`.
pub fn claim() -> Claim {
    Claim::default()
}

impl Claim {
    /// The `user` account of `claim` (signer, writable).
    ///
    /// Typed helper on [`Claim`], from the IDL's instructionAccountNode;
    /// takes a `Pubkey`, `&Pubkey`, or a cast member (`&Actor`).
    pub fn user(mut self, key: impl IntoAccountKey) -> Self {
        self.accounts.push(("user", key.into_account_key()));
        self
    }
    /// The `collection` account of `claim` (writable).
    ///
    /// Typed helper on [`Claim`], from the IDL's instructionAccountNode;
    /// takes a `Pubkey`, `&Pubkey`, or a cast member (`&Actor`).
    pub fn collection(mut self, key: impl IntoAccountKey) -> Self {
        self.accounts.push(("collection", key.into_account_key()));
        self
    }
    /// The `updateAuthority` account of `claim` (readonly; optional: omit it and the resolver fills the schema's default).
    ///
    /// Typed helper on [`Claim`], from the IDL's instructionAccountNode;
    /// takes a `Pubkey`, `&Pubkey`, or a cast member (`&Actor`).
    pub fn update_authority(mut self, key: impl IntoAccountKey) -> Self {
        self.accounts.push(("updateAuthority", key.into_account_key()));
        self
    }
    /// The `mint` account of `claim` (readonly).
    ///
    /// Typed helper on [`Claim`], from the IDL's instructionAccountNode;
    /// takes a `Pubkey`, `&Pubkey`, or a cast member (`&Actor`).
    pub fn mint(mut self, key: impl IntoAccountKey) -> Self {
        self.accounts.push(("mint", key.into_account_key()));
        self
    }
    /// The `campaignAta` account of `claim` (writable; optional: omit it and the resolver fills the schema's default).
    ///
    /// Typed helper on [`Claim`], from the IDL's instructionAccountNode;
    /// takes a `Pubkey`, `&Pubkey`, or a cast member (`&Actor`).
    pub fn campaign_ata(mut self, key: impl IntoAccountKey) -> Self {
        self.accounts.push(("campaignAta", key.into_account_key()));
        self
    }
    /// The `userAta` account of `claim` (writable; optional: omit it and the resolver fills the schema's default).
    ///
    /// Typed helper on [`Claim`], from the IDL's instructionAccountNode;
    /// takes a `Pubkey`, `&Pubkey`, or a cast member (`&Actor`).
    pub fn user_ata(mut self, key: impl IntoAccountKey) -> Self {
        self.accounts.push(("userAta", key.into_account_key()));
        self
    }
    /// The `campaign` account of `claim` (readonly; optional: omit it and the resolver fills the schema's default).
    ///
    /// Typed helper on [`Claim`], from the IDL's instructionAccountNode;
    /// takes a `Pubkey`, `&Pubkey`, or a cast member (`&Actor`).
    pub fn campaign(mut self, key: impl IntoAccountKey) -> Self {
        self.accounts.push(("campaign", key.into_account_key()));
        self
    }
    /// The `asset` account of `claim` (writable).
    ///
    /// Typed helper on [`Claim`], from the IDL's instructionAccountNode;
    /// takes a `Pubkey`, `&Pubkey`, or a cast member (`&Actor`).
    pub fn asset(mut self, key: impl IntoAccountKey) -> Self {
        self.accounts.push(("asset", key.into_account_key()));
        self
    }
    /// The `claimReceipt` account of `claim` (writable; optional: omit it and the resolver fills the schema's default).
    ///
    /// Typed helper on [`Claim`], from the IDL's instructionAccountNode;
    /// takes a `Pubkey`, `&Pubkey`, or a cast member (`&Actor`).
    pub fn claim_receipt(mut self, key: impl IntoAccountKey) -> Self {
        self.accounts.push(("claimReceipt", key.into_account_key()));
        self
    }
    /// The `systemProgram` account of `claim` (readonly; optional: omit it and the resolver fills the schema's default).
    ///
    /// Typed helper on [`Claim`], from the IDL's instructionAccountNode;
    /// takes a `Pubkey`, `&Pubkey`, or a cast member (`&Actor`).
    pub fn system_program(mut self, key: impl IntoAccountKey) -> Self {
        self.accounts.push(("systemProgram", key.into_account_key()));
        self
    }
    /// The `tokenProgram` account of `claim` (readonly; optional: omit it and the resolver fills the schema's default).
    ///
    /// Typed helper on [`Claim`], from the IDL's instructionAccountNode;
    /// takes a `Pubkey`, `&Pubkey`, or a cast member (`&Actor`).
    pub fn token_program(mut self, key: impl IntoAccountKey) -> Self {
        self.accounts.push(("tokenProgram", key.into_account_key()));
        self
    }
    /// The `associatedTokenProgram` account of `claim` (readonly; optional: omit it and the resolver fills the schema's default).
    ///
    /// Typed helper on [`Claim`], from the IDL's instructionAccountNode;
    /// takes a `Pubkey`, `&Pubkey`, or a cast member (`&Actor`).
    pub fn associated_token_program(mut self, key: impl IntoAccountKey) -> Self {
        self.accounts.push(("associatedTokenProgram", key.into_account_key()));
        self
    }
    /// The `mplCoreProgram` account of `claim` (readonly; optional: omit it and the resolver fills the schema's default).
    ///
    /// Typed helper on [`Claim`], from the IDL's instructionAccountNode;
    /// takes a `Pubkey`, `&Pubkey`, or a cast member (`&Actor`).
    pub fn mpl_core_program(mut self, key: impl IntoAccountKey) -> Self {
        self.accounts.push(("mplCoreProgram", key.into_account_key()));
        self
    }
    /// Set the `proofs` argument of `claim`.
    pub fn proofs(mut self, proofs: Option<Vec<Vec<u8>>>) -> Self {
        self.args.push(("proofs".into(), Value::Option(proofs.map(|x| Box::new(Value::Seq(x.into_iter().map(|x| Value::Bytes(x)).collect()))))));
        self
    }
    /// Set the `allocation` argument of `claim`.
    pub fn allocation(mut self, allocation: Option<u64>) -> Self {
        self.args.push(("allocation".into(), Value::Option(allocation.map(|x| Box::new(Value::U64(x))))));
        self
    }
    /// Set the `name` argument of `claim`.
    pub fn name(mut self, name: String) -> Self {
        self.args.push(("name".into(), Value::String(name)));
        self
    }
    /// Set the `uri` argument of `claim`.
    pub fn uri(mut self, uri: String) -> Self {
        self.args.push(("uri".into(), Value::String(uri)));
        self
    }
    /// Set every argument at once (see [`ClaimArgs`]); equivalent to the
    /// per-argument setters, for when the struct form reads cleaner.
    pub fn args(mut self, args: ClaimArgs) -> Self {
        if let Value::Struct(fields) = Value::from(args) {
            self.args = fields;
        }
        self
    }
}

impl TypedIx for Claim {
    const NAME: &'static str = "claim";
    fn lower(self) -> (Vec<(&'static str, Pubkey)>, Value) {
        (self.accounts, Value::Struct(self.args))
    }
}

impl IntoBundle for Claim {
    fn into_bundle(self, story: &Story) -> Vec<BuiltIx> {
        vec![story.ix_typed(self)]
    }
}

/// Typed builder for the `clawback` instruction of `vestingPositions`,
/// generated by `frood gen` from the program's Codama IDL. Each account
/// method is a compile-checked schema name; hand the builder to `Story::when`,
/// which lowers it to the same dynamic call the stringly form makes.
#[derive(Default)]
pub struct Clawback {
    accounts: Vec<(&'static str, Pubkey)>,
    args: Vec<(String, Value)>,
}

/// Start a typed `clawback` instruction (see [`Clawback`]).
///
/// Generated from `vestingPositions`'s Codama IDL; run it with `Story::when`.
pub fn clawback() -> Clawback {
    Clawback::default()
}

impl Clawback {
    /// The `creator` account of `clawback` (signer, writable).
    ///
    /// Typed helper on [`Clawback`], from the IDL's instructionAccountNode;
    /// takes a `Pubkey`, `&Pubkey`, or a cast member (`&Actor`).
    pub fn creator(mut self, key: impl IntoAccountKey) -> Self {
        self.accounts.push(("creator", key.into_account_key()));
        self
    }
    /// The `campaign` account of `clawback` (readonly; optional: omit it and the resolver fills the schema's default).
    ///
    /// Typed helper on [`Clawback`], from the IDL's instructionAccountNode;
    /// takes a `Pubkey`, `&Pubkey`, or a cast member (`&Actor`).
    pub fn campaign(mut self, key: impl IntoAccountKey) -> Self {
        self.accounts.push(("campaign", key.into_account_key()));
        self
    }
    /// The `collection` account of `clawback` (writable).
    ///
    /// Typed helper on [`Clawback`], from the IDL's instructionAccountNode;
    /// takes a `Pubkey`, `&Pubkey`, or a cast member (`&Actor`).
    pub fn collection(mut self, key: impl IntoAccountKey) -> Self {
        self.accounts.push(("collection", key.into_account_key()));
        self
    }
    /// The `updateAuthority` account of `clawback` (readonly; optional: omit it and the resolver fills the schema's default).
    ///
    /// Typed helper on [`Clawback`], from the IDL's instructionAccountNode;
    /// takes a `Pubkey`, `&Pubkey`, or a cast member (`&Actor`).
    pub fn update_authority(mut self, key: impl IntoAccountKey) -> Self {
        self.accounts.push(("updateAuthority", key.into_account_key()));
        self
    }
    /// The `asset` account of `clawback` (writable).
    ///
    /// Typed helper on [`Clawback`], from the IDL's instructionAccountNode;
    /// takes a `Pubkey`, `&Pubkey`, or a cast member (`&Actor`).
    pub fn asset(mut self, key: impl IntoAccountKey) -> Self {
        self.accounts.push(("asset", key.into_account_key()));
        self
    }
    /// The `mint` account of `clawback` (readonly).
    ///
    /// Typed helper on [`Clawback`], from the IDL's instructionAccountNode;
    /// takes a `Pubkey`, `&Pubkey`, or a cast member (`&Actor`).
    pub fn mint(mut self, key: impl IntoAccountKey) -> Self {
        self.accounts.push(("mint", key.into_account_key()));
        self
    }
    /// The `campaignAta` account of `clawback` (writable; optional: omit it and the resolver fills the schema's default).
    ///
    /// Typed helper on [`Clawback`], from the IDL's instructionAccountNode;
    /// takes a `Pubkey`, `&Pubkey`, or a cast member (`&Actor`).
    pub fn campaign_ata(mut self, key: impl IntoAccountKey) -> Self {
        self.accounts.push(("campaignAta", key.into_account_key()));
        self
    }
    /// The `creatorAta` account of `clawback` (writable; optional: omit it and the resolver fills the schema's default).
    ///
    /// Typed helper on [`Clawback`], from the IDL's instructionAccountNode;
    /// takes a `Pubkey`, `&Pubkey`, or a cast member (`&Actor`).
    pub fn creator_ata(mut self, key: impl IntoAccountKey) -> Self {
        self.accounts.push(("creatorAta", key.into_account_key()));
        self
    }
    /// The `systemProgram` account of `clawback` (readonly; optional: omit it and the resolver fills the schema's default).
    ///
    /// Typed helper on [`Clawback`], from the IDL's instructionAccountNode;
    /// takes a `Pubkey`, `&Pubkey`, or a cast member (`&Actor`).
    pub fn system_program(mut self, key: impl IntoAccountKey) -> Self {
        self.accounts.push(("systemProgram", key.into_account_key()));
        self
    }
    /// The `tokenProgram` account of `clawback` (readonly; optional: omit it and the resolver fills the schema's default).
    ///
    /// Typed helper on [`Clawback`], from the IDL's instructionAccountNode;
    /// takes a `Pubkey`, `&Pubkey`, or a cast member (`&Actor`).
    pub fn token_program(mut self, key: impl IntoAccountKey) -> Self {
        self.accounts.push(("tokenProgram", key.into_account_key()));
        self
    }
    /// The `associatedTokenProgram` account of `clawback` (readonly; optional: omit it and the resolver fills the schema's default).
    ///
    /// Typed helper on [`Clawback`], from the IDL's instructionAccountNode;
    /// takes a `Pubkey`, `&Pubkey`, or a cast member (`&Actor`).
    pub fn associated_token_program(mut self, key: impl IntoAccountKey) -> Self {
        self.accounts.push(("associatedTokenProgram", key.into_account_key()));
        self
    }
    /// The `mplCoreProgram` account of `clawback` (readonly; optional: omit it and the resolver fills the schema's default).
    ///
    /// Typed helper on [`Clawback`], from the IDL's instructionAccountNode;
    /// takes a `Pubkey`, `&Pubkey`, or a cast member (`&Actor`).
    pub fn mpl_core_program(mut self, key: impl IntoAccountKey) -> Self {
        self.accounts.push(("mplCoreProgram", key.into_account_key()));
        self
    }
}

impl TypedIx for Clawback {
    const NAME: &'static str = "clawback";
    fn lower(self) -> (Vec<(&'static str, Pubkey)>, Value) {
        (self.accounts, Value::Struct(self.args))
    }
}

impl IntoBundle for Clawback {
    fn into_bundle(self, story: &Story) -> Vec<BuiltIx> {
        vec![story.ix_typed(self)]
    }
}

/// Arguments of `clawbackUnclaimed`: a typed mirror of the instruction's Codama arguments, lowering to the dynamic `Value` at the border.
#[derive(Clone, Debug)]
pub struct ClawbackUnclaimedArgs {
    pub original_recipient: Pubkey,
    pub allocation: u64,
    pub proofs: Vec<Vec<u8>>,
}

impl From<ClawbackUnclaimedArgs> for Value {
    fn from(v: ClawbackUnclaimedArgs) -> Value {
        Value::Struct(vec![
            ("originalRecipient".into(), Value::Pubkey(v.original_recipient.to_bytes())),
            ("allocation".into(), Value::U64(v.allocation)),
            ("proofs".into(), Value::Seq(v.proofs.into_iter().map(|x| Value::Bytes(x)).collect())),
        ])
    }
}

/// Typed builder for the `clawbackUnclaimed` instruction of `vestingPositions`,
/// generated by `frood gen` from the program's Codama IDL. Each account
/// method is a compile-checked schema name; hand the builder to `Story::when`,
/// which lowers it to the same dynamic call the stringly form makes.
#[derive(Default)]
pub struct ClawbackUnclaimed {
    accounts: Vec<(&'static str, Pubkey)>,
    args: Vec<(String, Value)>,
}

/// Start a typed `clawbackUnclaimed` instruction (see [`ClawbackUnclaimed`]).
///
/// Generated from `vestingPositions`'s Codama IDL; run it with `Story::when`.
pub fn clawback_unclaimed() -> ClawbackUnclaimed {
    ClawbackUnclaimed::default()
}

impl ClawbackUnclaimed {
    /// The `creator` account of `clawbackUnclaimed` (signer, writable).
    ///
    /// Typed helper on [`ClawbackUnclaimed`], from the IDL's instructionAccountNode;
    /// takes a `Pubkey`, `&Pubkey`, or a cast member (`&Actor`).
    pub fn creator(mut self, key: impl IntoAccountKey) -> Self {
        self.accounts.push(("creator", key.into_account_key()));
        self
    }
    /// The `campaign` account of `clawbackUnclaimed` (readonly; optional: omit it and the resolver fills the schema's default).
    ///
    /// Typed helper on [`ClawbackUnclaimed`], from the IDL's instructionAccountNode;
    /// takes a `Pubkey`, `&Pubkey`, or a cast member (`&Actor`).
    pub fn campaign(mut self, key: impl IntoAccountKey) -> Self {
        self.accounts.push(("campaign", key.into_account_key()));
        self
    }
    /// The `collection` account of `clawbackUnclaimed` (readonly).
    ///
    /// Typed helper on [`ClawbackUnclaimed`], from the IDL's instructionAccountNode;
    /// takes a `Pubkey`, `&Pubkey`, or a cast member (`&Actor`).
    pub fn collection(mut self, key: impl IntoAccountKey) -> Self {
        self.accounts.push(("collection", key.into_account_key()));
        self
    }
    /// The `claimReceipt` account of `clawbackUnclaimed` (writable; optional: omit it and the resolver fills the schema's default).
    ///
    /// Typed helper on [`ClawbackUnclaimed`], from the IDL's instructionAccountNode;
    /// takes a `Pubkey`, `&Pubkey`, or a cast member (`&Actor`).
    pub fn claim_receipt(mut self, key: impl IntoAccountKey) -> Self {
        self.accounts.push(("claimReceipt", key.into_account_key()));
        self
    }
    /// The `asset` account of `clawbackUnclaimed` (readonly).
    ///
    /// Typed helper on [`ClawbackUnclaimed`], from the IDL's instructionAccountNode;
    /// takes a `Pubkey`, `&Pubkey`, or a cast member (`&Actor`).
    pub fn asset(mut self, key: impl IntoAccountKey) -> Self {
        self.accounts.push(("asset", key.into_account_key()));
        self
    }
    /// The `mint` account of `clawbackUnclaimed` (readonly).
    ///
    /// Typed helper on [`ClawbackUnclaimed`], from the IDL's instructionAccountNode;
    /// takes a `Pubkey`, `&Pubkey`, or a cast member (`&Actor`).
    pub fn mint(mut self, key: impl IntoAccountKey) -> Self {
        self.accounts.push(("mint", key.into_account_key()));
        self
    }
    /// The `campaignAta` account of `clawbackUnclaimed` (writable; optional: omit it and the resolver fills the schema's default).
    ///
    /// Typed helper on [`ClawbackUnclaimed`], from the IDL's instructionAccountNode;
    /// takes a `Pubkey`, `&Pubkey`, or a cast member (`&Actor`).
    pub fn campaign_ata(mut self, key: impl IntoAccountKey) -> Self {
        self.accounts.push(("campaignAta", key.into_account_key()));
        self
    }
    /// The `creatorAta` account of `clawbackUnclaimed` (writable; optional: omit it and the resolver fills the schema's default).
    ///
    /// Typed helper on [`ClawbackUnclaimed`], from the IDL's instructionAccountNode;
    /// takes a `Pubkey`, `&Pubkey`, or a cast member (`&Actor`).
    pub fn creator_ata(mut self, key: impl IntoAccountKey) -> Self {
        self.accounts.push(("creatorAta", key.into_account_key()));
        self
    }
    /// The `systemProgram` account of `clawbackUnclaimed` (readonly; optional: omit it and the resolver fills the schema's default).
    ///
    /// Typed helper on [`ClawbackUnclaimed`], from the IDL's instructionAccountNode;
    /// takes a `Pubkey`, `&Pubkey`, or a cast member (`&Actor`).
    pub fn system_program(mut self, key: impl IntoAccountKey) -> Self {
        self.accounts.push(("systemProgram", key.into_account_key()));
        self
    }
    /// The `tokenProgram` account of `clawbackUnclaimed` (readonly; optional: omit it and the resolver fills the schema's default).
    ///
    /// Typed helper on [`ClawbackUnclaimed`], from the IDL's instructionAccountNode;
    /// takes a `Pubkey`, `&Pubkey`, or a cast member (`&Actor`).
    pub fn token_program(mut self, key: impl IntoAccountKey) -> Self {
        self.accounts.push(("tokenProgram", key.into_account_key()));
        self
    }
    /// The `associatedTokenProgram` account of `clawbackUnclaimed` (readonly; optional: omit it and the resolver fills the schema's default).
    ///
    /// Typed helper on [`ClawbackUnclaimed`], from the IDL's instructionAccountNode;
    /// takes a `Pubkey`, `&Pubkey`, or a cast member (`&Actor`).
    pub fn associated_token_program(mut self, key: impl IntoAccountKey) -> Self {
        self.accounts.push(("associatedTokenProgram", key.into_account_key()));
        self
    }
    /// Set the `originalRecipient` argument of `clawbackUnclaimed`.
    pub fn original_recipient(mut self, original_recipient: Pubkey) -> Self {
        self.args.push(("originalRecipient".into(), Value::Pubkey(original_recipient.to_bytes())));
        self
    }
    /// Set the `allocation` argument of `clawbackUnclaimed`.
    pub fn allocation(mut self, allocation: u64) -> Self {
        self.args.push(("allocation".into(), Value::U64(allocation)));
        self
    }
    /// Set the `proofs` argument of `clawbackUnclaimed`.
    pub fn proofs(mut self, proofs: Vec<Vec<u8>>) -> Self {
        self.args.push(("proofs".into(), Value::Seq(proofs.into_iter().map(|x| Value::Bytes(x)).collect())));
        self
    }
    /// Set every argument at once (see [`ClawbackUnclaimedArgs`]); equivalent to the
    /// per-argument setters, for when the struct form reads cleaner.
    pub fn args(mut self, args: ClawbackUnclaimedArgs) -> Self {
        if let Value::Struct(fields) = Value::from(args) {
            self.args = fields;
        }
        self
    }
}

impl TypedIx for ClawbackUnclaimed {
    const NAME: &'static str = "clawbackUnclaimed";
    fn lower(self) -> (Vec<(&'static str, Pubkey)>, Value) {
        (self.accounts, Value::Struct(self.args))
    }
}

impl IntoBundle for ClawbackUnclaimed {
    fn into_bundle(self, story: &Story) -> Vec<BuiltIx> {
        vec![story.ix_typed(self)]
    }
}

/// Typed builder for the `closeCampaign` instruction of `vestingPositions`,
/// generated by `frood gen` from the program's Codama IDL. Each account
/// method is a compile-checked schema name; hand the builder to `Story::when`,
/// which lowers it to the same dynamic call the stringly form makes.
#[derive(Default)]
pub struct CloseCampaign {
    accounts: Vec<(&'static str, Pubkey)>,
    args: Vec<(String, Value)>,
}

/// Start a typed `closeCampaign` instruction (see [`CloseCampaign`]).
///
/// Generated from `vestingPositions`'s Codama IDL; run it with `Story::when`.
pub fn close_campaign() -> CloseCampaign {
    CloseCampaign::default()
}

impl CloseCampaign {
    /// The `creator` account of `closeCampaign` (signer, writable).
    ///
    /// Typed helper on [`CloseCampaign`], from the IDL's instructionAccountNode;
    /// takes a `Pubkey`, `&Pubkey`, or a cast member (`&Actor`).
    pub fn creator(mut self, key: impl IntoAccountKey) -> Self {
        self.accounts.push(("creator", key.into_account_key()));
        self
    }
    /// The `campaign` account of `closeCampaign` (writable; optional: omit it and the resolver fills the schema's default).
    ///
    /// Typed helper on [`CloseCampaign`], from the IDL's instructionAccountNode;
    /// takes a `Pubkey`, `&Pubkey`, or a cast member (`&Actor`).
    pub fn campaign(mut self, key: impl IntoAccountKey) -> Self {
        self.accounts.push(("campaign", key.into_account_key()));
        self
    }
    /// The `collection` account of `closeCampaign` (readonly).
    ///
    /// Typed helper on [`CloseCampaign`], from the IDL's instructionAccountNode;
    /// takes a `Pubkey`, `&Pubkey`, or a cast member (`&Actor`).
    pub fn collection(mut self, key: impl IntoAccountKey) -> Self {
        self.accounts.push(("collection", key.into_account_key()));
        self
    }
    /// The `mint` account of `closeCampaign` (readonly).
    ///
    /// Typed helper on [`CloseCampaign`], from the IDL's instructionAccountNode;
    /// takes a `Pubkey`, `&Pubkey`, or a cast member (`&Actor`).
    pub fn mint(mut self, key: impl IntoAccountKey) -> Self {
        self.accounts.push(("mint", key.into_account_key()));
        self
    }
    /// The `campaignAta` account of `closeCampaign` (writable; optional: omit it and the resolver fills the schema's default).
    ///
    /// Typed helper on [`CloseCampaign`], from the IDL's instructionAccountNode;
    /// takes a `Pubkey`, `&Pubkey`, or a cast member (`&Actor`).
    pub fn campaign_ata(mut self, key: impl IntoAccountKey) -> Self {
        self.accounts.push(("campaignAta", key.into_account_key()));
        self
    }
    /// The `tokenProgram` account of `closeCampaign` (readonly; optional: omit it and the resolver fills the schema's default).
    ///
    /// Typed helper on [`CloseCampaign`], from the IDL's instructionAccountNode;
    /// takes a `Pubkey`, `&Pubkey`, or a cast member (`&Actor`).
    pub fn token_program(mut self, key: impl IntoAccountKey) -> Self {
        self.accounts.push(("tokenProgram", key.into_account_key()));
        self
    }
}

impl TypedIx for CloseCampaign {
    const NAME: &'static str = "closeCampaign";
    fn lower(self) -> (Vec<(&'static str, Pubkey)>, Value) {
        (self.accounts, Value::Struct(self.args))
    }
}

impl IntoBundle for CloseCampaign {
    fn into_bundle(self, story: &Story) -> Vec<BuiltIx> {
        vec![story.ix_typed(self)]
    }
}

/// Typed builder for the `closeReceipt` instruction of `vestingPositions`,
/// generated by `frood gen` from the program's Codama IDL. Each account
/// method is a compile-checked schema name; hand the builder to `Story::when`,
/// which lowers it to the same dynamic call the stringly form makes.
#[derive(Default)]
pub struct CloseReceipt {
    accounts: Vec<(&'static str, Pubkey)>,
    args: Vec<(String, Value)>,
}

/// Start a typed `closeReceipt` instruction (see [`CloseReceipt`]).
///
/// Generated from `vestingPositions`'s Codama IDL; run it with `Story::when`.
pub fn close_receipt() -> CloseReceipt {
    CloseReceipt::default()
}

impl CloseReceipt {
    /// The `user` account of `closeReceipt` (signer, writable).
    ///
    /// Typed helper on [`CloseReceipt`], from the IDL's instructionAccountNode;
    /// takes a `Pubkey`, `&Pubkey`, or a cast member (`&Actor`).
    pub fn user(mut self, key: impl IntoAccountKey) -> Self {
        self.accounts.push(("user", key.into_account_key()));
        self
    }
    /// The `campaign` account of `closeReceipt` (readonly).
    ///
    /// Typed helper on [`CloseReceipt`], from the IDL's instructionAccountNode;
    /// takes a `Pubkey`, `&Pubkey`, or a cast member (`&Actor`).
    pub fn campaign(mut self, key: impl IntoAccountKey) -> Self {
        self.accounts.push(("campaign", key.into_account_key()));
        self
    }
    /// The `claimReceipt` account of `closeReceipt` (writable; optional: omit it and the resolver fills the schema's default).
    ///
    /// Typed helper on [`CloseReceipt`], from the IDL's instructionAccountNode;
    /// takes a `Pubkey`, `&Pubkey`, or a cast member (`&Actor`).
    pub fn claim_receipt(mut self, key: impl IntoAccountKey) -> Self {
        self.accounts.push(("claimReceipt", key.into_account_key()));
        self
    }
}

impl TypedIx for CloseReceipt {
    const NAME: &'static str = "closeReceipt";
    fn lower(self) -> (Vec<(&'static str, Pubkey)>, Value) {
        (self.accounts, Value::Struct(self.args))
    }
}

impl IntoBundle for CloseReceipt {
    fn into_bundle(self, story: &Story) -> Vec<BuiltIx> {
        vec![story.ix_typed(self)]
    }
}

/// Typed builder for the `excludeAsset` instruction of `vestingPositions`,
/// generated by `frood gen` from the program's Codama IDL. Each account
/// method is a compile-checked schema name; hand the builder to `Story::when`,
/// which lowers it to the same dynamic call the stringly form makes.
#[derive(Default)]
pub struct ExcludeAsset {
    accounts: Vec<(&'static str, Pubkey)>,
    args: Vec<(String, Value)>,
}

/// Start a typed `excludeAsset` instruction (see [`ExcludeAsset`]).
///
/// Generated from `vestingPositions`'s Codama IDL; run it with `Story::when`.
pub fn exclude_asset() -> ExcludeAsset {
    ExcludeAsset::default()
}

impl ExcludeAsset {
    /// The `creator` account of `excludeAsset` (signer, writable).
    ///
    /// Typed helper on [`ExcludeAsset`], from the IDL's instructionAccountNode;
    /// takes a `Pubkey`, `&Pubkey`, or a cast member (`&Actor`).
    pub fn creator(mut self, key: impl IntoAccountKey) -> Self {
        self.accounts.push(("creator", key.into_account_key()));
        self
    }
    /// The `campaign` account of `excludeAsset` (readonly; optional: omit it and the resolver fills the schema's default).
    ///
    /// Typed helper on [`ExcludeAsset`], from the IDL's instructionAccountNode;
    /// takes a `Pubkey`, `&Pubkey`, or a cast member (`&Actor`).
    pub fn campaign(mut self, key: impl IntoAccountKey) -> Self {
        self.accounts.push(("campaign", key.into_account_key()));
        self
    }
    /// The `collection` account of `excludeAsset` (writable).
    ///
    /// Typed helper on [`ExcludeAsset`], from the IDL's instructionAccountNode;
    /// takes a `Pubkey`, `&Pubkey`, or a cast member (`&Actor`).
    pub fn collection(mut self, key: impl IntoAccountKey) -> Self {
        self.accounts.push(("collection", key.into_account_key()));
        self
    }
    /// The `updateAuthority` account of `excludeAsset` (readonly; optional: omit it and the resolver fills the schema's default).
    ///
    /// Typed helper on [`ExcludeAsset`], from the IDL's instructionAccountNode;
    /// takes a `Pubkey`, `&Pubkey`, or a cast member (`&Actor`).
    pub fn update_authority(mut self, key: impl IntoAccountKey) -> Self {
        self.accounts.push(("updateAuthority", key.into_account_key()));
        self
    }
    /// The `asset` account of `excludeAsset` (writable).
    ///
    /// Typed helper on [`ExcludeAsset`], from the IDL's instructionAccountNode;
    /// takes a `Pubkey`, `&Pubkey`, or a cast member (`&Actor`).
    pub fn asset(mut self, key: impl IntoAccountKey) -> Self {
        self.accounts.push(("asset", key.into_account_key()));
        self
    }
    /// The `mint` account of `excludeAsset` (readonly).
    ///
    /// Typed helper on [`ExcludeAsset`], from the IDL's instructionAccountNode;
    /// takes a `Pubkey`, `&Pubkey`, or a cast member (`&Actor`).
    pub fn mint(mut self, key: impl IntoAccountKey) -> Self {
        self.accounts.push(("mint", key.into_account_key()));
        self
    }
    /// The `campaignAta` account of `excludeAsset` (writable; optional: omit it and the resolver fills the schema's default).
    ///
    /// Typed helper on [`ExcludeAsset`], from the IDL's instructionAccountNode;
    /// takes a `Pubkey`, `&Pubkey`, or a cast member (`&Actor`).
    pub fn campaign_ata(mut self, key: impl IntoAccountKey) -> Self {
        self.accounts.push(("campaignAta", key.into_account_key()));
        self
    }
    /// The `creatorAta` account of `excludeAsset` (writable; optional: omit it and the resolver fills the schema's default).
    ///
    /// Typed helper on [`ExcludeAsset`], from the IDL's instructionAccountNode;
    /// takes a `Pubkey`, `&Pubkey`, or a cast member (`&Actor`).
    pub fn creator_ata(mut self, key: impl IntoAccountKey) -> Self {
        self.accounts.push(("creatorAta", key.into_account_key()));
        self
    }
    /// The `systemProgram` account of `excludeAsset` (readonly; optional: omit it and the resolver fills the schema's default).
    ///
    /// Typed helper on [`ExcludeAsset`], from the IDL's instructionAccountNode;
    /// takes a `Pubkey`, `&Pubkey`, or a cast member (`&Actor`).
    pub fn system_program(mut self, key: impl IntoAccountKey) -> Self {
        self.accounts.push(("systemProgram", key.into_account_key()));
        self
    }
    /// The `tokenProgram` account of `excludeAsset` (readonly; optional: omit it and the resolver fills the schema's default).
    ///
    /// Typed helper on [`ExcludeAsset`], from the IDL's instructionAccountNode;
    /// takes a `Pubkey`, `&Pubkey`, or a cast member (`&Actor`).
    pub fn token_program(mut self, key: impl IntoAccountKey) -> Self {
        self.accounts.push(("tokenProgram", key.into_account_key()));
        self
    }
    /// The `associatedTokenProgram` account of `excludeAsset` (readonly; optional: omit it and the resolver fills the schema's default).
    ///
    /// Typed helper on [`ExcludeAsset`], from the IDL's instructionAccountNode;
    /// takes a `Pubkey`, `&Pubkey`, or a cast member (`&Actor`).
    pub fn associated_token_program(mut self, key: impl IntoAccountKey) -> Self {
        self.accounts.push(("associatedTokenProgram", key.into_account_key()));
        self
    }
    /// The `mplCoreProgram` account of `excludeAsset` (readonly; optional: omit it and the resolver fills the schema's default).
    ///
    /// Typed helper on [`ExcludeAsset`], from the IDL's instructionAccountNode;
    /// takes a `Pubkey`, `&Pubkey`, or a cast member (`&Actor`).
    pub fn mpl_core_program(mut self, key: impl IntoAccountKey) -> Self {
        self.accounts.push(("mplCoreProgram", key.into_account_key()));
        self
    }
}

impl TypedIx for ExcludeAsset {
    const NAME: &'static str = "excludeAsset";
    fn lower(self) -> (Vec<(&'static str, Pubkey)>, Value) {
        (self.accounts, Value::Struct(self.args))
    }
}

impl IntoBundle for ExcludeAsset {
    fn into_bundle(self, story: &Story) -> Vec<BuiltIx> {
        vec![story.ix_typed(self)]
    }
}

/// Arguments of `freezeAsset`: a typed mirror of the instruction's Codama arguments, lowering to the dynamic `Value` at the border.
#[derive(Clone, Debug)]
pub struct FreezeAssetArgs {
    pub should_freeze: bool,
}

impl From<FreezeAssetArgs> for Value {
    fn from(v: FreezeAssetArgs) -> Value {
        Value::Struct(vec![
            ("shouldFreeze".into(), Value::Bool(v.should_freeze)),
        ])
    }
}

/// Typed builder for the `freezeAsset` instruction of `vestingPositions`,
/// generated by `frood gen` from the program's Codama IDL. Each account
/// method is a compile-checked schema name; hand the builder to `Story::when`,
/// which lowers it to the same dynamic call the stringly form makes.
#[derive(Default)]
pub struct FreezeAsset {
    accounts: Vec<(&'static str, Pubkey)>,
    args: Vec<(String, Value)>,
}

/// Start a typed `freezeAsset` instruction (see [`FreezeAsset`]).
///
/// Generated from `vestingPositions`'s Codama IDL; run it with `Story::when`.
pub fn freeze_asset() -> FreezeAsset {
    FreezeAsset::default()
}

impl FreezeAsset {
    /// The `creator` account of `freezeAsset` (signer, writable).
    ///
    /// Typed helper on [`FreezeAsset`], from the IDL's instructionAccountNode;
    /// takes a `Pubkey`, `&Pubkey`, or a cast member (`&Actor`).
    pub fn creator(mut self, key: impl IntoAccountKey) -> Self {
        self.accounts.push(("creator", key.into_account_key()));
        self
    }
    /// The `campaign` account of `freezeAsset` (readonly; optional: omit it and the resolver fills the schema's default).
    ///
    /// Typed helper on [`FreezeAsset`], from the IDL's instructionAccountNode;
    /// takes a `Pubkey`, `&Pubkey`, or a cast member (`&Actor`).
    pub fn campaign(mut self, key: impl IntoAccountKey) -> Self {
        self.accounts.push(("campaign", key.into_account_key()));
        self
    }
    /// The `collection` account of `freezeAsset` (writable).
    ///
    /// Typed helper on [`FreezeAsset`], from the IDL's instructionAccountNode;
    /// takes a `Pubkey`, `&Pubkey`, or a cast member (`&Actor`).
    pub fn collection(mut self, key: impl IntoAccountKey) -> Self {
        self.accounts.push(("collection", key.into_account_key()));
        self
    }
    /// The `updateAuthority` account of `freezeAsset` (readonly; optional: omit it and the resolver fills the schema's default).
    ///
    /// Typed helper on [`FreezeAsset`], from the IDL's instructionAccountNode;
    /// takes a `Pubkey`, `&Pubkey`, or a cast member (`&Actor`).
    pub fn update_authority(mut self, key: impl IntoAccountKey) -> Self {
        self.accounts.push(("updateAuthority", key.into_account_key()));
        self
    }
    /// The `asset` account of `freezeAsset` (writable).
    ///
    /// Typed helper on [`FreezeAsset`], from the IDL's instructionAccountNode;
    /// takes a `Pubkey`, `&Pubkey`, or a cast member (`&Actor`).
    pub fn asset(mut self, key: impl IntoAccountKey) -> Self {
        self.accounts.push(("asset", key.into_account_key()));
        self
    }
    /// The `systemProgram` account of `freezeAsset` (readonly; optional: omit it and the resolver fills the schema's default).
    ///
    /// Typed helper on [`FreezeAsset`], from the IDL's instructionAccountNode;
    /// takes a `Pubkey`, `&Pubkey`, or a cast member (`&Actor`).
    pub fn system_program(mut self, key: impl IntoAccountKey) -> Self {
        self.accounts.push(("systemProgram", key.into_account_key()));
        self
    }
    /// The `mplCoreProgram` account of `freezeAsset` (readonly; optional: omit it and the resolver fills the schema's default).
    ///
    /// Typed helper on [`FreezeAsset`], from the IDL's instructionAccountNode;
    /// takes a `Pubkey`, `&Pubkey`, or a cast member (`&Actor`).
    pub fn mpl_core_program(mut self, key: impl IntoAccountKey) -> Self {
        self.accounts.push(("mplCoreProgram", key.into_account_key()));
        self
    }
    /// Set the `shouldFreeze` argument of `freezeAsset`.
    pub fn should_freeze(mut self, should_freeze: bool) -> Self {
        self.args.push(("shouldFreeze".into(), Value::Bool(should_freeze)));
        self
    }
    /// Set every argument at once (see [`FreezeAssetArgs`]); equivalent to the
    /// per-argument setters, for when the struct form reads cleaner.
    pub fn args(mut self, args: FreezeAssetArgs) -> Self {
        if let Value::Struct(fields) = Value::from(args) {
            self.args = fields;
        }
        self
    }
}

impl TypedIx for FreezeAsset {
    const NAME: &'static str = "freezeAsset";
    fn lower(self) -> (Vec<(&'static str, Pubkey)>, Value) {
        (self.accounts, Value::Struct(self.args))
    }
}

impl IntoBundle for FreezeAsset {
    fn into_bundle(self, story: &Story) -> Vec<BuiltIx> {
        vec![story.ix_typed(self)]
    }
}

/// Arguments of `freezeCollection`: a typed mirror of the instruction's Codama arguments, lowering to the dynamic `Value` at the border.
#[derive(Clone, Debug)]
pub struct FreezeCollectionArgs {
    pub should_freeze: bool,
}

impl From<FreezeCollectionArgs> for Value {
    fn from(v: FreezeCollectionArgs) -> Value {
        Value::Struct(vec![
            ("shouldFreeze".into(), Value::Bool(v.should_freeze)),
        ])
    }
}

/// Typed builder for the `freezeCollection` instruction of `vestingPositions`,
/// generated by `frood gen` from the program's Codama IDL. Each account
/// method is a compile-checked schema name; hand the builder to `Story::when`,
/// which lowers it to the same dynamic call the stringly form makes.
#[derive(Default)]
pub struct FreezeCollection {
    accounts: Vec<(&'static str, Pubkey)>,
    args: Vec<(String, Value)>,
}

/// Start a typed `freezeCollection` instruction (see [`FreezeCollection`]).
///
/// Generated from `vestingPositions`'s Codama IDL; run it with `Story::when`.
pub fn freeze_collection() -> FreezeCollection {
    FreezeCollection::default()
}

impl FreezeCollection {
    /// The `creator` account of `freezeCollection` (signer, writable).
    ///
    /// Typed helper on [`FreezeCollection`], from the IDL's instructionAccountNode;
    /// takes a `Pubkey`, `&Pubkey`, or a cast member (`&Actor`).
    pub fn creator(mut self, key: impl IntoAccountKey) -> Self {
        self.accounts.push(("creator", key.into_account_key()));
        self
    }
    /// The `campaign` account of `freezeCollection` (writable; optional: omit it and the resolver fills the schema's default).
    ///
    /// Typed helper on [`FreezeCollection`], from the IDL's instructionAccountNode;
    /// takes a `Pubkey`, `&Pubkey`, or a cast member (`&Actor`).
    pub fn campaign(mut self, key: impl IntoAccountKey) -> Self {
        self.accounts.push(("campaign", key.into_account_key()));
        self
    }
    /// The `collection` account of `freezeCollection` (writable).
    ///
    /// Typed helper on [`FreezeCollection`], from the IDL's instructionAccountNode;
    /// takes a `Pubkey`, `&Pubkey`, or a cast member (`&Actor`).
    pub fn collection(mut self, key: impl IntoAccountKey) -> Self {
        self.accounts.push(("collection", key.into_account_key()));
        self
    }
    /// The `updateAuthority` account of `freezeCollection` (readonly; optional: omit it and the resolver fills the schema's default).
    ///
    /// Typed helper on [`FreezeCollection`], from the IDL's instructionAccountNode;
    /// takes a `Pubkey`, `&Pubkey`, or a cast member (`&Actor`).
    pub fn update_authority(mut self, key: impl IntoAccountKey) -> Self {
        self.accounts.push(("updateAuthority", key.into_account_key()));
        self
    }
    /// The `systemProgram` account of `freezeCollection` (readonly; optional: omit it and the resolver fills the schema's default).
    ///
    /// Typed helper on [`FreezeCollection`], from the IDL's instructionAccountNode;
    /// takes a `Pubkey`, `&Pubkey`, or a cast member (`&Actor`).
    pub fn system_program(mut self, key: impl IntoAccountKey) -> Self {
        self.accounts.push(("systemProgram", key.into_account_key()));
        self
    }
    /// The `mplCoreProgram` account of `freezeCollection` (readonly; optional: omit it and the resolver fills the schema's default).
    ///
    /// Typed helper on [`FreezeCollection`], from the IDL's instructionAccountNode;
    /// takes a `Pubkey`, `&Pubkey`, or a cast member (`&Actor`).
    pub fn mpl_core_program(mut self, key: impl IntoAccountKey) -> Self {
        self.accounts.push(("mplCoreProgram", key.into_account_key()));
        self
    }
    /// Set the `shouldFreeze` argument of `freezeCollection`.
    pub fn should_freeze(mut self, should_freeze: bool) -> Self {
        self.args.push(("shouldFreeze".into(), Value::Bool(should_freeze)));
        self
    }
    /// Set every argument at once (see [`FreezeCollectionArgs`]); equivalent to the
    /// per-argument setters, for when the struct form reads cleaner.
    pub fn args(mut self, args: FreezeCollectionArgs) -> Self {
        if let Value::Struct(fields) = Value::from(args) {
            self.args = fields;
        }
        self
    }
}

impl TypedIx for FreezeCollection {
    const NAME: &'static str = "freezeCollection";
    fn lower(self) -> (Vec<(&'static str, Pubkey)>, Value) {
        (self.accounts, Value::Struct(self.args))
    }
}

impl IntoBundle for FreezeCollection {
    fn into_bundle(self, story: &Story) -> Vec<BuiltIx> {
        vec![story.ix_typed(self)]
    }
}

/// Arguments of `initialize`: a typed mirror of the instruction's Codama arguments, lowering to the dynamic `Value` at the border.
#[derive(Clone, Debug)]
pub struct InitializeArgs {
    pub merkle_root: Vec<u8>,
    pub start: i64,
    pub end: i64,
    pub cliff_duration: u64,
    pub cliff_release_bps: u16,
    pub mint_to_distribute: Pubkey,
    pub is_transferable: bool,
    pub grace_period: u64,
    pub total_deposit: u64,
    pub name: String,
    pub uri: String,
}

impl From<InitializeArgs> for Value {
    fn from(v: InitializeArgs) -> Value {
        Value::Struct(vec![
            ("merkleRoot".into(), Value::Bytes(v.merkle_root)),
            ("start".into(), Value::I64(v.start)),
            ("end".into(), Value::I64(v.end)),
            ("cliffDuration".into(), Value::U64(v.cliff_duration)),
            ("cliffReleaseBps".into(), Value::U16(v.cliff_release_bps)),
            ("mintToDistribute".into(), Value::Pubkey(v.mint_to_distribute.to_bytes())),
            ("isTransferable".into(), Value::Bool(v.is_transferable)),
            ("gracePeriod".into(), Value::U64(v.grace_period)),
            ("totalDeposit".into(), Value::U64(v.total_deposit)),
            ("name".into(), Value::String(v.name)),
            ("uri".into(), Value::String(v.uri)),
        ])
    }
}

/// Typed builder for the `initialize` instruction of `vestingPositions`,
/// generated by `frood gen` from the program's Codama IDL. Each account
/// method is a compile-checked schema name; hand the builder to `Story::when`,
/// which lowers it to the same dynamic call the stringly form makes.
#[derive(Default)]
pub struct Initialize {
    accounts: Vec<(&'static str, Pubkey)>,
    args: Vec<(String, Value)>,
}

/// Start a typed `initialize` instruction (see [`Initialize`]).
///
/// Generated from `vestingPositions`'s Codama IDL; run it with `Story::when`.
pub fn initialize() -> Initialize {
    Initialize::default()
}

impl Initialize {
    /// The `creator` account of `initialize` (signer, writable).
    ///
    /// Typed helper on [`Initialize`], from the IDL's instructionAccountNode;
    /// takes a `Pubkey`, `&Pubkey`, or a cast member (`&Actor`).
    pub fn creator(mut self, key: impl IntoAccountKey) -> Self {
        self.accounts.push(("creator", key.into_account_key()));
        self
    }
    /// The `collection` account of `initialize` (writable; optional: omit it and the resolver fills the schema's default).
    ///
    /// Typed helper on [`Initialize`], from the IDL's instructionAccountNode;
    /// takes a `Pubkey`, `&Pubkey`, or a cast member (`&Actor`).
    pub fn collection(mut self, key: impl IntoAccountKey) -> Self {
        self.accounts.push(("collection", key.into_account_key()));
        self
    }
    /// The `updateAuthority` account of `initialize` (readonly; optional: omit it and the resolver fills the schema's default).
    ///
    /// Typed helper on [`Initialize`], from the IDL's instructionAccountNode;
    /// takes a `Pubkey`, `&Pubkey`, or a cast member (`&Actor`).
    pub fn update_authority(mut self, key: impl IntoAccountKey) -> Self {
        self.accounts.push(("updateAuthority", key.into_account_key()));
        self
    }
    /// The `mint` account of `initialize` (writable).
    ///
    /// Typed helper on [`Initialize`], from the IDL's instructionAccountNode;
    /// takes a `Pubkey`, `&Pubkey`, or a cast member (`&Actor`).
    pub fn mint(mut self, key: impl IntoAccountKey) -> Self {
        self.accounts.push(("mint", key.into_account_key()));
        self
    }
    /// The `creatorAta` account of `initialize` (writable; optional: omit it and the resolver fills the schema's default).
    ///
    /// Typed helper on [`Initialize`], from the IDL's instructionAccountNode;
    /// takes a `Pubkey`, `&Pubkey`, or a cast member (`&Actor`).
    pub fn creator_ata(mut self, key: impl IntoAccountKey) -> Self {
        self.accounts.push(("creatorAta", key.into_account_key()));
        self
    }
    /// The `campaign` account of `initialize` (writable; optional: omit it and the resolver fills the schema's default).
    ///
    /// Typed helper on [`Initialize`], from the IDL's instructionAccountNode;
    /// takes a `Pubkey`, `&Pubkey`, or a cast member (`&Actor`).
    pub fn campaign(mut self, key: impl IntoAccountKey) -> Self {
        self.accounts.push(("campaign", key.into_account_key()));
        self
    }
    /// The `campaignAta` account of `initialize` (writable; optional: omit it and the resolver fills the schema's default).
    ///
    /// Typed helper on [`Initialize`], from the IDL's instructionAccountNode;
    /// takes a `Pubkey`, `&Pubkey`, or a cast member (`&Actor`).
    pub fn campaign_ata(mut self, key: impl IntoAccountKey) -> Self {
        self.accounts.push(("campaignAta", key.into_account_key()));
        self
    }
    /// The `systemProgram` account of `initialize` (readonly; optional: omit it and the resolver fills the schema's default).
    ///
    /// Typed helper on [`Initialize`], from the IDL's instructionAccountNode;
    /// takes a `Pubkey`, `&Pubkey`, or a cast member (`&Actor`).
    pub fn system_program(mut self, key: impl IntoAccountKey) -> Self {
        self.accounts.push(("systemProgram", key.into_account_key()));
        self
    }
    /// The `tokenProgram` account of `initialize` (readonly; optional: omit it and the resolver fills the schema's default).
    ///
    /// Typed helper on [`Initialize`], from the IDL's instructionAccountNode;
    /// takes a `Pubkey`, `&Pubkey`, or a cast member (`&Actor`).
    pub fn token_program(mut self, key: impl IntoAccountKey) -> Self {
        self.accounts.push(("tokenProgram", key.into_account_key()));
        self
    }
    /// The `associatedTokenProgram` account of `initialize` (readonly; optional: omit it and the resolver fills the schema's default).
    ///
    /// Typed helper on [`Initialize`], from the IDL's instructionAccountNode;
    /// takes a `Pubkey`, `&Pubkey`, or a cast member (`&Actor`).
    pub fn associated_token_program(mut self, key: impl IntoAccountKey) -> Self {
        self.accounts.push(("associatedTokenProgram", key.into_account_key()));
        self
    }
    /// The `mplCoreProgram` account of `initialize` (readonly; optional: omit it and the resolver fills the schema's default).
    ///
    /// Typed helper on [`Initialize`], from the IDL's instructionAccountNode;
    /// takes a `Pubkey`, `&Pubkey`, or a cast member (`&Actor`).
    pub fn mpl_core_program(mut self, key: impl IntoAccountKey) -> Self {
        self.accounts.push(("mplCoreProgram", key.into_account_key()));
        self
    }
    /// Set the `merkleRoot` argument of `initialize`.
    pub fn merkle_root(mut self, merkle_root: Vec<u8>) -> Self {
        self.args.push(("merkleRoot".into(), Value::Bytes(merkle_root)));
        self
    }
    /// Set the `start` argument of `initialize`.
    pub fn start(mut self, start: i64) -> Self {
        self.args.push(("start".into(), Value::I64(start)));
        self
    }
    /// Set the `end` argument of `initialize`.
    pub fn end(mut self, end: i64) -> Self {
        self.args.push(("end".into(), Value::I64(end)));
        self
    }
    /// Set the `cliffDuration` argument of `initialize`.
    pub fn cliff_duration(mut self, cliff_duration: u64) -> Self {
        self.args.push(("cliffDuration".into(), Value::U64(cliff_duration)));
        self
    }
    /// Set the `cliffReleaseBps` argument of `initialize`.
    pub fn cliff_release_bps(mut self, cliff_release_bps: u16) -> Self {
        self.args.push(("cliffReleaseBps".into(), Value::U16(cliff_release_bps)));
        self
    }
    /// Set the `mintToDistribute` argument of `initialize`.
    pub fn mint_to_distribute(mut self, mint_to_distribute: Pubkey) -> Self {
        self.args.push(("mintToDistribute".into(), Value::Pubkey(mint_to_distribute.to_bytes())));
        self
    }
    /// Set the `isTransferable` argument of `initialize`.
    pub fn is_transferable(mut self, is_transferable: bool) -> Self {
        self.args.push(("isTransferable".into(), Value::Bool(is_transferable)));
        self
    }
    /// Set the `gracePeriod` argument of `initialize`.
    pub fn grace_period(mut self, grace_period: u64) -> Self {
        self.args.push(("gracePeriod".into(), Value::U64(grace_period)));
        self
    }
    /// Set the `totalDeposit` argument of `initialize`.
    pub fn total_deposit(mut self, total_deposit: u64) -> Self {
        self.args.push(("totalDeposit".into(), Value::U64(total_deposit)));
        self
    }
    /// Set the `name` argument of `initialize`.
    pub fn name(mut self, name: String) -> Self {
        self.args.push(("name".into(), Value::String(name)));
        self
    }
    /// Set the `uri` argument of `initialize`.
    pub fn uri(mut self, uri: String) -> Self {
        self.args.push(("uri".into(), Value::String(uri)));
        self
    }
    /// Set every argument at once (see [`InitializeArgs`]); equivalent to the
    /// per-argument setters, for when the struct form reads cleaner.
    pub fn args(mut self, args: InitializeArgs) -> Self {
        if let Value::Struct(fields) = Value::from(args) {
            self.args = fields;
        }
        self
    }
}

impl TypedIx for Initialize {
    const NAME: &'static str = "initialize";
    fn lower(self) -> (Vec<(&'static str, Pubkey)>, Value) {
        (self.accounts, Value::Struct(self.args))
    }
}

impl IntoBundle for Initialize {
    fn into_bundle(self, story: &Story) -> Vec<BuiltIx> {
        vec![story.ix_typed(self)]
    }
}

